// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDykgAtWsrabuJ6q7CSLyuGKTkGQ9Y0RY',
    appId: '1:547081194951:web:cc0c5669efdbc569cf1de2',
    messagingSenderId: '547081194951',
    projectId: 'visitjordan-d6998',
    authDomain: 'visitjordan-d6998.firebaseapp.com',
    storageBucket: 'visitjordan-d6998.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDV3XqVszJ3uFUQplY-BCDBj-fej7_431o',
    appId: '1:547081194951:android:6dedfab16db90186cf1de2',
    messagingSenderId: '547081194951',
    projectId: 'visitjordan-d6998',
    storageBucket: 'visitjordan-d6998.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBk5ok012yIzWpgwROlq1b5Umx25Qw2R_Y',
    appId: '1:547081194951:ios:7590e7b775e4b364cf1de2',
    messagingSenderId: '547081194951',
    projectId: 'visitjordan-d6998',
    storageBucket: 'visitjordan-d6998.appspot.com',
    iosClientId: '547081194951-8n5h3pjdjpnmgtckgabn1nlder3h2rj5.apps.googleusercontent.com',
    iosBundleId: 'com.example.visitjordan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBk5ok012yIzWpgwROlq1b5Umx25Qw2R_Y',
    appId: '1:547081194951:ios:7590e7b775e4b364cf1de2',
    messagingSenderId: '547081194951',
    projectId: 'visitjordan-d6998',
    storageBucket: 'visitjordan-d6998.appspot.com',
    iosClientId: '547081194951-8n5h3pjdjpnmgtckgabn1nlder3h2rj5.apps.googleusercontent.com',
    iosBundleId: 'com.example.visitjordan',
  );
}
